# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/dbt_project.json

# name: "my_dbt_project"
# version: "1.0"
# config-version: 2

# profile: "my_postgres_profile"

# models:
#   my_dbt_project:
#     +schema: public
#     +materialized: view



name: "my_dbt_project"  # Name of your project
version: "1.0.0"
config-version: 2

profile: "my_postgres_profile"  # Profile name (must match profiles.yml)

# Define where dbt should look for models
model-paths: ["models"]

# Store compiled SQL and logs
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:  # Project name (should match the `name` field)
    staging:
      +materialized: view  # Use 'view' for staging models
    mart:
      +materialized: table  # Use 'table' for transformed models
